name: "Biome Code Quality Assurance"

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  quality:
    runs-on: "ubuntu-latest"

    permissions:
      contents: "write"

    steps:
      - name: "Checkout code"
        uses: "actions/checkout@v4"
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"

      - name: "Setup Biome"
        uses: "biomejs/setup-biome@v2"
        with:
          version: "latest"

      - name: "Format with Biome"
        run: "biome format --write ."

      - name: "Run Biome CI check (to be reported later)"
        id: "biome-check"
        run: |
          # Don't exit on error
          set +e
          biome ci . 2>&1 | tee biome-output.log
          BIOME_EXIT_CODE=${PIPESTATUS[0]}
          
          echo "success=$([ $BIOME_EXIT_CODE -eq 0 ] && echo true || echo false)" >> "$GITHUB_OUTPUT"

      - name: "Check for Git changes"
        id: "verify-changed-files"
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

      - name: "Commit Git changes"
        if: steps.verify-changed-files.outputs.changed == 'true' && github.event_name == 'push'
        run: |
          git -c user.name="github-actions[bot]" -c user.email="41898282+github-actions[bot]@users.noreply.github.com" \
            commit -am "chore: auto-fix formatting and linting with Biome"

      - name: "Push Git changes"
        if: steps.verify-changed-files.outputs.changed == 'true' && github.event_name == 'push'
        uses: "ad-m/github-push-action@master"
        with:
          github_token: "${{ secrets.GITHUB_TOKEN }}"
          branch: "${{ github.ref_name }}"

      - name: "Fail if Biome CI check failed"
        if: steps.biome-check.outputs.success == 'false'
        run: |
          echo "Biome CI check failed. Output:"
          cat biome-output.log
          exit 1

